language: emacs-lisp
sudo: false

matrix:
  include:
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-24.1-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-24.2-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-24.3-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-24.4-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-24.5-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-25.1-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-25.2-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-25.3-travis
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-26.1-travis-linux-xenial
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-26.2-travis-linux-xenial
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-26.3-travis-linux-xenial
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-27.1-travis-linux-xenial
    - os: linux
      dist: xenial
      env: EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

before_script:
  # - sudo apt-get update
  # - sudo apt-get install libgnutls30 gnutls-bin -y
  - mv -f ../.emacs.d ~/.emacs.d
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  # - export PATH="/home/travis/.cask/bin:$PATH"
  - evm config path /tmp
  # - curl -fsSkL https://raw.githubusercontent.com/cask/cask/master/go | python
  - evm install $EVM_EMACS --use --skip
  # - mkdir -p lib && curl https://raw.githubusercontent.com/nschum/elisp-lint/stable/elisp-lint.el > lib/elisp-lint.el

script:
  - ${EMACS:=emacs} --version
  - echo "Attempting startup..."
  - ${EMACS:=emacs} -nw --batch --eval
    '(let ((debug-on-error (>=  emacs-major-version 26))
    (url-show-status nil)
    (user-emacs-directory default-directory)
    (early-init-file (expand-file-name "early-init.el"))
    (user-init-file (expand-file-name "init.el"))
    (load-path (delq default-directory load-path)))
    (when (>= emacs-major-version 27) (load-file early-init-file))
    (load-file user-init-file)
    (when (>= emacs-major-version 26)
    (run-hooks (quote after-init-hook))
    (run-hooks (quote emacs-startup-hook))))'
  - echo "Startup successful"
